(define-key global-map "\M-[1~" 'beginning-of-line)
(define-key global-map [select] 'end-of-line)
(define-key global-map "\M-[C" 'custom-forward-word)
(define-key global-map "\M-[D" 'custom-backward-word)
(define-key global-map "\M-[A" 'custom-next-buffer)
(define-key global-map "\M-[B" 'custom-prev-buffer)
