(defun color-theme-custom-dark ()
  (interactive)
  (color-theme-install
   '(color-theme-custom-dark
      ((background-color . "#000000")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#4e9cb7")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (region ((t (:background "#333333"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#5e5e5e"))))
     (font-lock-function-name-face ((t (:foreground "#ddb540"))))
     (font-lock-keyword-face ((t (:foreground "#729fcf"))))
     (font-lock-string-face ((t (:foreground "#53b441"))))
     (font-lock-type-face ((t (:foreground"#e27c34"))))
     (font-lock-constant-face ((t (:foreground "#e6a00f"))))
     (font-lock-variable-name-face ((t (:foreground "#729fcf"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-custom-dark)
